---
# Custom Caddy config for the insights-chrome-dev container to serve static assets on port 9912
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrome-dev-caddyfile
data:
  # The key here will be the filename inside the container
  Caddyfile: |
    {
      debug
    }

    :9912 {
        root * /opt/app-root/src/build/stable

        # Handle /apps/chrome* requests - strip prefix and serve
        @app_match {
            path /apps/chrome*
        }
        handle @app_match {
            uri strip_prefix /apps/chrome
            file_server {
                browse
            }
        }

        # Handle all other requests - serve files normally
        handle {
            file_server
        }

        header {
            Cache-Control "no-cache, no-store, must-revalidate"
            Pragma "no-cache"
            Expires "0"
        }
        header {
            Access-Control-Allow-Origin "*"
            Access-Control-Allow-Methods "GET, POST, OPTIONS"
            Access-Control-Allow-Headers "Content-Type"
        }
    }