---
# Custom Caddy config for the insights-chrome-dev container to serve static assets on port 9912
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrome-dev-caddyfile
data:
  # The key here will be the filename inside the container
  Caddyfile: |
    :9912 {
        root * /opt/app-root/src/build/stable
        file_server
        header {
               Cache-Control "no-cache, no-store, must-revalidate"
               Pragma "no-cache"
               Expires "0"
               }
        header {
               Access-Control-Allow-Origin "*"
               Access-Control-Allow-Methods "GET, POST, OPTIONS"
               Access-Control-Allow-Headers "Content-Type"
               }
      }