---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-task
spec:
  params:
    - description: The Trusted Artifact URI.
      name: SOURCE_ARTIFACT
      type: string
    - description: The script to execute the e2e tests
      name: e2e-tests-script
      type: string
    - description: http proxy config
      name: HTTP_PROXY
      type: string
    - description: Test user
      name: E2E_USER
      type: string
    - description: Test user password
      name: E2E_PASSWORD
      type: string
  sidecars:
    - image: quay.io/redhat-user-workloads/hcc-platex-services-tenant/frontend-development-proxy:latest
      name: frontend-dev-proxy
      env:
        - name: HTTP_PROXY
          value: $(params.HTTP_PROXY)
        - name: HTTPS_PROXY
          value: $(params.HTTP_PROXY)
      securityContext:
        privileged: false
      volumeMounts:
        - name: frontend-proxy-routes
          mountPath: /config/routes.json
          subPath: routes.json
    - image: quay.io/redhat-services-prod/hcc-platex-services-tenant/insights-chrome-dev:latest
      name: insights-chrome-dev
      command: ["caddy"]
      args: ["run", "--config", "/Caddyfile"]
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
        - name: chrome-dev-caddyfile
          mountPath: /Caddyfile
          subPath: Caddyfile
    - name: run-learning-resources
      image: $(params.SOURCE_ARTIFACT)
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
  volumes:
    - name: workdir
      emptyDir: {}
    - name: chrome-dev-caddyfile
      configMap:
        name: chrome-dev-caddyfile
    - name: frontend-proxy-routes
      configMap:
        name: frontend-proxy-routes
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
        readOnly: false
  steps:
    - image: quay.io/btweed/playwright_e2e:latest
      env:
        - name: HTTP_PROXY
          value: $(params.HTTP_PROXY)
        - name: HTTPS_PROXY
          value: $(params.HTTP_PROXY)
        - name: E2E_USER
          value: $(params.E2E_USER)
        - name: E2E_PASSWORD
          value: $(params.E2E_PASSWORD)
        - name: NO_PROXY
          value: "stage.foo.redhat.com"
      name: e2e-tests
      computeResources:
        requests:
          cpu: "2000m"
          memory: "4Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
      securityContext:
        runAsUser: 0
      script: $(params.e2e-tests-script)
  workspaces:
    - name: shared-code-workspace
      mountPath: /workspace/output
