apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-task
spec:
  params:
    - description: The Trusted Artifact URI pointing to the artifact with the application source code.
      name: SOURCE_ARTIFACT
      type: string
    - description: The script to execute the e2e tests
      name: e2e-tests-script
      type: string
  sidecars:
    - image: quay.io/redhat-user-workloads/hcc-platex-services-tenant/frontend-development-proxy:latest
      name: frontend-dev-proxy
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
    - name: run-learning-resources
      image: $(params.SOURCE_ARTIFACT)
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
        readOnly: false
  steps:
    # - image: cypress/included:cypress-15.3.0-node-22.20.0-chrome-140.0.7339.207-1-ff-143.0.1-edge-140.0.3485.81-1
    - image: $(params.SOURCE_ARTIFACT)
      workingDir: /var/workdir
      name: e2e-tests
      args:
        - user
        - $(params.SOURCE_ARTIFACT)=/var/workdir
      securityContext:
        runAsUser: 0
      script: $(params.e2e-tests-script)

