---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-task
spec:
  podTemplate:
    shareProcessNamespace: true
  params:
    - description: The Trusted Artifact URI.
      name: SOURCE_ARTIFACT
      type: string
    - description: The script to execute the e2e tests
      name: e2e-tests-script
      type: string
  sidecars:
    - image: quay.io/redhat-user-workloads/hcc-platex-services-tenant/frontend-development-proxy:latest
      name: frontend-dev-proxy
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
    - name: run-learning-resources
      image: $(params.SOURCE_ARTIFACT)
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
  volumes:
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
        readOnly: false
  steps:
    - image: quay.io/btweed/cypress:latest
      name: e2e-tests
      computeResources:
        requests:
          cpu: "4"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
      securityContext:
        runAsUser: 0
      script: $(params.e2e-tests-script)
  workspaces:
    - name: shared-code-workspace
      mountPath: /workspace/output
