apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: e2e-task-run
spec:
  params:
    - name: SOURCE_ARTIFACT
      value: quay.io/redhat-services-prod/hcc-platex-services-tenant/learning-resources:latest
    - name: e2e-tests-script
      value: |
         npm run start &
         npx cypress run --e2e
  taskRef:
    name: e2e-task
