---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: e2e-pipeline-run
spec:
  params:
    - name: branch-name
      value: btweed/e2e
    - name: repo-url
      value: https://github.com/RedHatInsights/learning-resources.git
    - name: SOURCE_ARTIFACT
      value: quay.io/redhat-services-prod/hcc-platex-services-tenant/learning-resources:latest
    - name: E2E_USER
      value: "${E2E_USER}"
    - name: E2E_PASSWORD
      value: "${E2E_PASSWORD}"
    - name: e2e_proxy
      value: "${E2E_PROXY_URL}"
  workspaces:
    - name: shared-code-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  pipelineRef:
    name: e2e-pipeline
  taskRunSpecs:
    - pipelineTaskName: e2e-test-run
      podTemplate:
        hostAliases:
          - ip: "127.0.0.1"
            hostnames:
              - "stage.foo.redhat.com"
