---
# Custom routes configuration for the frontend-development-proxy container
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-proxy-routes
data:
  routes.json: |
    {
      "/index.html": {
        "url": "http://localhost:9912",
        "is_chrome": true
      },
      "/apps/chrome*": {
        "url": "http://localhost:9912",
        "is_chrome": true
      },
      "/apps/learning-resources*": {
        "url": "http://localhost:8000"
      },
      "/settings/learning-resources*": {
        "url": "http://localhost:8000"
      },
      "/openshift/learning-resources*":  {
        "url": "http://localhost:8000"
      },    
      "/ansible/learning-resources*":  {
        "url": "http://localhost:8000"
      },
      "/insights/learning-resources*":  {
        "url": "http://localhost:8000"
      },
      "/edge/learning-resources*":  {
        "url": "http://localhost:8000"
      },
      "/iam/learning-resources*":  {
        "url": "http://localhost:8000"
      },
      "/learning-resources*":  {
        "url": "http://localhost:8000"
      },
      "/learning-resources/creator*": {
        "url": "http://localhost:8000"
      }
    }
